#%RAML 1.0 
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/5a875b07-2a03-441a-8b50-d67d9055b4eb/ # 
title: API-led connectivity - Exchange documentation templates

documentation:
  - !include docs-templates/api-home-page.raml
  - !include docs-templates/api-technical-view.raml
  - !include docs-templates/api-reusable-assets.raml
  - !include docs-templates/api-integration-details.raml
  - !include docs-templates/api-workspace.raml
  - !include docs-templates/api-policies.raml
  - !include docs-templates/api-release-notes.raml
  - !include docs-templates/api-acronyms.raml
  - !include docs-templates/api-faq.raml
  