#%RAML 1.0 DocumentationItem
title: Release Notes
content: |

  ### **Version 1.0.8 - Oct 16, 2019**
  _** Deprecation date: Oct 16, 2020**_

  This release of ACME Banking API added the following features to the api.

  - Allowing user to set a maximum number or rows in result
  - Defaulting ssn query parameter to 0 and make it optional
  - Defaulting type query parameter to Customer and make it optional
  - Fixing api interface issue, removing the maximum number of result from a unique customer search

  ### **Version 1.0.7 - Oct 10, 2019**
  _** Deprecation date: Jan 16, 2020**_

  This release of ACME banking API added the following features to the api.

  - Adding 90% coverage for Munit
