#%RAML 1.0 DocumentationItem
title: Reusable Assets
content: |
  #### There are few reusable assets used by ACME Banking as a best practice approach

  #### Please visit the following pages for more details about each asset.

  ### Development Assets

  #### Common Data Models

  **Description:** Common data models defined and shared across different services. [More details...](refer to the asset exchange URL)

  **Copyrights©:** X Bank

  #### Common Fragments

  **Description:** Common fragments and traits defines the security and error codes shared across different services. [More details...](refer to the asset exchange URL)

  **Copyrights©:** X Bank

  ### Other Assets

  #### Exchange Icon

  ![resources/1104720-36a38978-0d42-4df7-91e1-bea1937126c9.svg](https://cdn3.iconfinder.com/data/icons/man-user-human-avatar-profile-person-business/100/04-1User_5-2-512.png)

  **Description:** ACME Banking Lookup icon for exchange [More details...](https://cdn3.iconfinder.com/data/icons/man-user-human-avatar-profile-person-business/100/04-1User_5-2-512.png)

  **Copyrights©: ** [FlatIcon - Basic License](https://file000.flaticon.com/downloads/license/license.pdf)

  This is to be used internally. For external use please review the license.