#%RAML 1.0 DocumentationItem
title: Acronyms
content: |  
  Below is a list of appreviation used in the documentation to describe the system implementation and the integration pieces. 
  <div class="content-IIWFV"><article id="asset-page-content" class="asset-page-3w8Rl" data-test-id="asset-page" aria-labelledby="asset-page-name"><div class="header-2DVT7"><h2 class="" id="asset-page-name" data-test-id="asset-page-name"></h2></div><div class="page-11SaW" data-test-id="asset-page-content"><table>
  <tbody>
  <tr>
  <td>
  Acronym
  </td>
  <td>
  Stands for
  </td>
  <td>
  Description
  </td>
  </tr>
  <tr>
  <td>
  API
  </td>
  <td>
  Application Programming Interface
  </td>
  <td>
  Method for computer systems to exchange data using defined standards and formats
  </td>
  </tr>
  <tr>
  <td>
  JSON
  </td>
  <td>
  Java Script Object Notation
  </td>
  <td>
  An open-standard file format that uses human-readable text to transmit data objects
  Consists of attribute–value pairs and array data types
  </td>
  </tr>
  <tr>
  <td>
  RAML
  </td>
  <td>
  Restful API Modelling Language
  </td>
  <td>
  Used to document API design at X Bank
  </td>
  </tr>

  <tr>
  <td>
  DPID
  </td>
  <td>
  SSN
  </td>
  <td>
  a customer social security number
  </td>
  </tr>

  <tr>
  <td>
  DQS
  </td>
  <td>
  Data Quality Services
  </td>
  <td>
  X Bank services which are cleansing the data from the duplication, dummy and invalid data and expose them as HTTP/REST service
  </td>
  </tr>

 
  
  </tbody>

  </table> </div></article></div>
