#%RAML 1.0 DocumentationItem
title: FAQ
content: |
  To get support from our team and view the status of the APIs, view our Support page.

  Please review the following questions before contacting support team

  **What is ACME Banking API ?**

  The ACME Banking API is a HTTP/REST service  enable search for

  - a customer information using the customer name, date of birth. API returns list of matching customers. No data cleansing involved in case of multiple customers returned by a unique identifer 
  - a unique customer information using date of birth, passport number or national security id. Only one customer is returned from the system.

  Please refer to this [page](refer to the home page) for more details. 

  **What is the latest version of ACME Banking API ?**

  Please refer to [Release notes](refer to release notes page) for more details about versions 

  **How to Integrate with ACME Banking API ?**

  There are different ways of integration based on different criterias. Please refer [Integration details](refer to integration details page) page for more details.

  **What happens if I can’t find a customer?**

  If you are sure that the customer is valid, then log an inquiry with API Support.

  **What is the master source of the customer details?**

  Please review the following pages for more information about the source of information

  - [ACME Banking API Source](refer to more details about the API)
  

  **What are applied policies and restrictions to this ACME Banking API? **

  ACME Banking API has few applied policies

  1. Client ID enforcement 
  2. Spike Control
  3. CORS

  Please refer to the following [page](refer to API policies page) for more details. 

  _More details required to be added by the client, but this is a sample of what could it be_