#%RAML 1.0 DocumentationItem
title: Technical Overview
description: The provided information into this page is not a real case and the images are only captured for simulation purpose. All images can be added to the project resources and exposed in exchange 
content: | 
  ### **ACME Banking API Architecture Overview**

  X Bank is following API-led connectivity approach to implement ACME banking API solution. ACME banking  API is delivered as an experience layer api to enable integration with the customer information base in the bank.


  Below diagram shows how the Address lookup api fits into the architecture.

  ![https://blogs.mulesoft.com/wp-content/uploads/API-led-architecture-blog.jpg](https://blogs.mulesoft.com/wp-content/uploads/API-led-architecture-blog.jpg)

  ### **ACME Banking in the business landscape** 
  Below diagram shows how the ACME banking api fits into the current business landscape.

  ![https://pubs.opengroup.org/dpbok/standard/images/2_99-architectural-view.png](https://pubs.opengroup.org/dpbok/standard/images/2_99-architectural-view.png)

  ### **ACME Banking API Use case (Views) **

  acme-banking-exp-api refers to ACME banking api. 

  ACME banking api is used to provide a digital user experience for the client by providing the customer with all profile details and customising the customer experience by recommending appropriate offers that user can purchase (e.g. Credit Card)

   _Add more details about the usecase if required. It's good to show how it fits in the big picture._
  
  **Logical View: **
  below diagram shows the transactions between systems in sequence. _Add a bit of details about the flow. If there is systems abbreviations used in the diargram, then refer to Acronym table._

  ![https://i.pinimg.com/originals/44/17/80/441780789545bae1fcfabaaa78c23ef1.png](https://i.pinimg.com/originals/44/17/80/441780789545bae1fcfabaaa78c23ef1.png)

  **Development View**
  _Add a bit of details about the flow. If there is systems abbreviations used in the diargram, then refer to Acronym table._
  _This section is an optional and it's preferred if you can add very high level view about the integration pattern. 

  ![http://eaipatterns.com/img/WgrusOrders1.gif](http://eaipatterns.com/img/WgrusOrders1.gif)

  **Physical View**
  _Add a bit of details about the flow. If there is systems abbreviations used in the diargram, then refer to Acronym table._
  ![https://docs.mulesoft.com/runtime-manager/_images/chvpc02.png](https://docs.mulesoft.com/runtime-manager/_images/chvpc02.png)

  ** DevOps Physical View**
  _Add a bit of details about the flow. If there is systems abbreviations used in the diargram, then refer to Acronym table._ 
  ![https://dzone.com/storage/temp/11064215-capture.jpg](https://dzone.com/storage/temp/11064215-capture.jpg)