#%RAML 1.0 DocumentationItem
title: Home
description: The provided information into this page is not a real case and the images are only captured for simulation purpose. 
content: |
  # **What is the ACME Banking API?**
  The Acme Banking API enables search for 

  - a customer information using the customer name, date of birth. API returns list of matching customers. No data cleansing involved in case of multiple customers returned by a unique identifer 
  - a unique customer information using date of birth, passport number or national security id. Only one customer is returned from the system.

  The ACME banking API can also be integrated directly with your systems.

  The ACME banking API uses X bank CRM system to retreive customer information.
  

